# Generated by Django 4.1.7 on 2023-04-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_student_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='sttudent',
        ),
    ]
