# Generated by Django 4.1.7 on 2023-04-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0006_rename_user_submission_sttudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='sttudent',
            new_name='student',
        ),
    ]
