# Generated by Django 4.1.7 on 2023-04-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0008_alter_submission_student_assesment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assesment',
            new_name='Assessment',
        ),
    ]
