# Generated by Django 4.1.7 on 2023-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0009_rename_assesment_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
